general.import = [
  "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
TERM = "xterm-256color"

[window]
#padding.x = 8
#padding.y = 8

dynamic_padding = true

dimensions = { columns = 124, lines = 31 }

#opacity  = 0.90
#blur = true

#startup_mode = "Fullscreen"

option_as_alt = "Both"

#decorations = "None"

[selection]
save_to_clipboard = true

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Bold"

size = 14

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
draw_bold_text_with_bright_colors = true

[cursor]
style.blinking = "Always"
unfocused_hollow = true

[mouse]
hide_when_typing = true 
bindings = [
{ mouse = "Right", mods = "Shift", action = "Paste" },
]

[keyboard]
bindings = [
{key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
{key = "F", mods = "Control|Shift", action = "ToggleFullScreen"},
{key = "Q", mods = "Control|Shift", action = "Quit"},
]

